repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.347
    hooks:
    - id: pyright

  - repo: https://github.com/FHPythonUtils/Blackt
    rev: '2024'
    hooks:
      - id: blackt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/boidolr/pre-commit-images
    rev: v1.5.1
    hooks:
      - id: optimize-jpg
      - id: optimize-png
      - id: optimize-svg
      - id: optimize-webp

exclude: "tests/data|documentation/reference"
