[tool.poetry]
name = "layeredimage"
version = "2020.2.1"
description = "Use this module to read, and write to a number of layered image formats"
authors = ["FredHappyface"]
classifiers = [
	"Programming Language :: Python :: 3.6",
	"Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Operating System :: OS Independent"
]
homepage = "https://github.com/FHPythonUtils/LayeredImage"
repository = "https://github.com/FHPythonUtils/LayeredImage"
documentation = "https://github.com/FHPythonUtils/LayeredImage/blob/master/README.md"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
defusedxml = "^0.6.0"
metprint = "^2020.5"
pillow = "^7.1.1"
pyora = "^0.3.0"
scikit-image = "^0.16.2"
numpy = "^1.18.3"
pypdn = { version = "^1.0.3", optional = true }
psd-tools3 = { version = "^1.8.2", optional = true }
gimpformats-unofficial = { version = "^0.1", optional = true }

[tool.dephell.main]
from = "pyproject.toml"
to = "requirements.txt"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
