[tool.poetry]
name = "layeredimage"
version = "2020.5.4"
description = "Use this module to read, and write to a number of layered image formats"
authors = ["FredHappyface"]
classifiers = [
	"Programming Language :: Python :: 3.6",
	"Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Operating System :: OS Independent"
]
homepage = "https://github.com/FHPythonUtils/LayeredImage"
repository = "https://github.com/FHPythonUtils/LayeredImage"
documentation = "https://github.com/FHPythonUtils/LayeredImage/blob/master/README.md"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
defusedxml = "^0.6.0"
metprint = "^2020.5"
pillow = "^7.1.2"
pyora = "^0.3.0"
pypdn = "^1.0.5"
psd-tools3 = "^1.8.2"
gimpformats-unofficial = "^0.1"
pylsr = "^2020.0.2"
blendmodes = "^2020.2"

[tool.poetry.dev-dependencies]
imgcompare = "^2.0.1"

[tool.dephell.main]
from = "pyproject.toml"
to = "requirements.txt"
envs = ["main"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
